development:
  adapter: postgresql
  encoding: utf8
  database: alice_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: alice_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: alice_production
  pool: 5
  username:
  password:
